config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'tasks#home'

  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new

  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :show

  get "tasks/:id/edit", to: "tasks#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def home
  end

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to show_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/home.html.erb
<h1>Welcome to Task Manager</h1>

<%= link_to "List of Tasks", tasks_path %>

app/views/tasks/index.html.erb
<h2>List of Tasks</h2>
<p>Click a tasks to see it's details.</p>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, show_path(task) %></li>
  <% end %>
</ul>
<br>
<%= link_to "Add new Task", new_path %>
<br>
<%= link_to "Back to Home page", root_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.label :completed %>
<%= f.text_field :completed %>
<%= f.submit %>
<% end %>

<br>
<%= link_to "List of Tasks", tasks_path %>
<br>
<%= link_to "Back to Home page", root_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<%= link_to "Back to Tasks", tasks_path %>